export { default as DiseasesTable } from "./disease";
export { default as ModelsTable } from "./model";
export { default as PatientsTable } from "./patient";
export { default as PredictionsTable } from "./prediction";
export { default as PredictionRequestsTable } from "./prediction_request";
export { default as PredictionClassesTable } from "./prediction_class_disease";
export { default as UserProfilesTable } from "./user_profile";
export { default as FeedbackTable } from "./feedback";
export { default as PredictionSharingTable } from "./prediction_sharing";
